name: INVOICE APP CI
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: lint
        uses: super-linter/super-linter@v6.3.0
      - name: build
        run: npm run build
